### ISSUE TITLE
TypeError [2]: Não foi possível carregar a DLL.

### ISSUE THREAD

**Issue by fitinge** [danielccunha/node-sitef#1]
Estou tentando rodar seu projeto e sempre retorna esse erro. 
O caminho seria da CliSitef32I.dll ou libclisitef.so? Testei ambos e nenhum vai. 
Sabe se está faltando alguma configuração ou algum passo que não realizei?

**Comment by ddanielcruz** [comment]
É o caminho completo para o **libclisitef.so**. Utilizo da seguinte maneira:

```js
const path = require("path");

module.exports = {
    dllPath: path.resolve(__dirname, "..", "bin/libclisitef.so")
};
```

Nesse caso mantenho as DLLs em uma pasta **bin** e a configuração do Sitef em uma pasta **config**. Basta montar o caminho da DLL dessa maneira que o Sitef deve ser carregado corretamente.

**Comment by fefurst** [comment]
Lembrando que CliSitef32I.dll é para windows e libclisitef.so é para linux.
Atenção também para a arquitetura utilizada, 32 ou 64 bits, o módulo do sitef deve seguir a mesma do executável do node.
