### ISSUE TITLE
Problemas com Electron

### ISSUE THREAD

**Issue by joaodematejr** [danielccunha/node-sitef#4]
Estou tentando usar a biblioteca com eletron mas fica acusando esse erro, 

![image](https://user-images.githubusercontent.com/17418041/120088911-d5a22700-c0cb-11eb-99f8-be2fef092364.png)

![image](https://user-images.githubusercontent.com/17418041/120088920-f0749b80-c0cb-11eb-90e1-19201602f93a.png)

`// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')
const path = require('path')

const SiTef = require('node-sitef');

const dlls = path.resolve(__dirname, 'bin', 'CliSiTef64I.dll');
const sitef = new SiTef(dlls);

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
`

**Comment by fefurst** [comment]
Seu SO é 32bits ou 64bits? Electron é 32 bits e a DLL 64 ? Revise os módulos se são da mesma arquitetura.

**Comment by joaodematejr** [comment]
> Seu SO é 32bits ou 64bits? Electron é 32 bits e a DLL 64 ? Revise os módulos se são da mesma arquitetura.

Sistema é 64 Bits/ Node tb é 64 Bits e a DLL tb é 64 Bits, até estou pensando em migrar tudo para 32bits pra testar.
